/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_file_server_scan_ScanJni */

#ifndef _Included_com_file_server_scan_ScanJni
#define _Included_com_file_server_scan_ScanJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_file_server_scan_ScanJni
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_file_server_scan_ScanJni_stringFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_file_server_scan_ScanJni
 * Method:    scanRootPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_file_server_scan_ScanJni_scanRootPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_file_server_scan_ScanJni
 * Method:    getPY
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_com_file_server_scan_ScanJni_getPY
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
